// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class PlayerDataServiceBindings
    {
        readonly ICloudCodeService k_Service;
        public PlayerDataServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<Project.PlayerDataResponse> HandlePlayerSignIn(string authPlayerName)
        {
            return await k_Service.CallModuleEndpointAsync<Project.PlayerDataResponse>(
                "Project",
                "HandlePlayerSignIn",
                new Dictionary<string, object>()
                {
                    {"authPlayerName", authPlayerName},
                });
        }

        public async Task<Project.PlayerData> UpdateGameRecord(int newScore, int newSurviveTime, int clearStageLevel)
        {
            return await k_Service.CallModuleEndpointAsync<Project.PlayerData>(
                "Project",
                "UpdateGameRecord",
                new Dictionary<string, object>()
                {
                    {"newScore", newScore},
                    {"newSurviveTime", newSurviveTime},
                    {"clearStageLevel", clearStageLevel},
                });
        }

        public async Task<Project.PlayerUpgradeData> UpdateUpgradeLevel(string upgradeType, int newLevel)
        {
            return await k_Service.CallModuleEndpointAsync<Project.PlayerUpgradeData>(
                "Project",
                "UpdateUpgradeLevel",
                new Dictionary<string, object>()
                {
                    {"upgradeType", upgradeType},
                    {"newLevel", newLevel},
                });
        }
    }
}
