// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class PlayerDataServiceBindings
    {
        readonly ICloudCodeService k_Service;
        public PlayerDataServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<Project.PlayerDataResponse> HandlePlayerSignIn(string authPlayerName)
        {
            return await k_Service.CallModuleEndpointAsync<Project.PlayerDataResponse>(
                "Project",
                "HandlePlayerSignIn",
                new Dictionary<string, object>()
                {
                    {"authPlayerName", authPlayerName},
                });
        }
    }
}
