// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class PlayerEconomyServiceBindings
    {
        readonly ICloudCodeService k_Service;
        public PlayerEconomyServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<Project.PlayerEconomyData> HandleSpendCurrency(string currencyKey, int amount)
        {
            return await k_Service.CallModuleEndpointAsync<Project.PlayerEconomyData>(
                "Project",
                "HandleSpendCurrency",
                new Dictionary<string, object>()
                {
                    {"currencyKey", currencyKey},
                    {"amount", amount},
                });
        }

        public async Task<Project.PlayerEconomyData> HandleAddCurrency(string currencyKey, int amount)
        {
            return await k_Service.CallModuleEndpointAsync<Project.PlayerEconomyData>(
                "Project",
                "HandleAddCurrency",
                new Dictionary<string, object>()
                {
                    {"currencyKey", currencyKey},
                    {"amount", amount},
                });
        }

        public async Task<Project.PlayerEconomyData> GetPlayerEconomyData()
        {
            return await k_Service.CallModuleEndpointAsync<Project.PlayerEconomyData>(
                "Project",
                "GetPlayerEconomyData",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<int> GetInventoryItemAmount(string key)
        {
            return await k_Service.CallModuleEndpointAsync<int>(
                "Project",
                "GetInventoryItemAmount",
                new Dictionary<string, object>()
                {
                    {"key", key},
                });
        }
    }
}
