// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class PlayerDataServiceBindings
    {
        readonly ICloudCodeService k_Service;
        public PlayerDataServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task SayHello(string key, string value)
        {
            await k_Service.CallModuleEndpointAsync(
                "Project",
                "SayHello",
                new Dictionary<string, object>()
                {
                    {"key", key},
                    {"value", value},
                });
        }
    }
}
