// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.Project
{
    public partial class EquipmentItemData
    {
        public string InstanceId;
        public string ItemKey;
        public int Level;
        public int Amount;

        [Preserve]
        public EquipmentItemData ()
        {
        }
    }
}