// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.Project
{
    public partial class PlayerUpgradeData
    {
        public Dictionary<string,int> UpgradeLevels;

        [Preserve]
        public PlayerUpgradeData ()
        {
        }
    }
}