// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.Project
{
    public partial class PlayerData
    {
        public string DisplayName;
        public int Experience;
        public int MaxSurviveTime;
        public int MaxScore;

        [Preserve]
        public PlayerData ()
        {
        }
    }
}