// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class StoreServiceBindings
    {
        readonly ICloudCodeService k_Service;
        public StoreServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<Project.PlayerEconomyData> PurchaseVirtualItem(string purchaseId)
        {
            return await k_Service.CallModuleEndpointAsync<Project.PlayerEconomyData>(
                "Project",
                "PurchaseVirtualItem",
                new Dictionary<string, object>()
                {
                    {"purchaseId", purchaseId},
                });
        }

        public async Task<Project.PlayerEconomyData> ProcessRealMoneyPurchase(string productId, string receipt, double localPrice, string currencyCode)
        {
            return await k_Service.CallModuleEndpointAsync<Project.PlayerEconomyData>(
                "Project",
                "ProcessRealMoneyPurchase",
                new Dictionary<string, object>()
                {
                    {"productId", productId},
                    {"receipt", receipt},
                    {"localPrice", localPrice},
                    {"currencyCode", currencyCode},
                });
        }

        public async Task<Project.PlayerEconomyData> ClaimDailyFreeReward(int amount)
        {
            return await k_Service.CallModuleEndpointAsync<Project.PlayerEconomyData>(
                "Project",
                "ClaimDailyFreeReward",
                new Dictionary<string, object>()
                {
                    {"amount", amount},
                });
        }
    }
}
